# Generated by Django 5.2.5 on 2025-10-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_diamonds_user_level_user_xp_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='condition_type',
            field=models.CharField(blank=True, choices=[('login_days', 'Zile de logare'), ('integrame_rezolvate', 'Integrame rezolvate'), ('level', 'Nivel atins')], help_text='Tipul condiției pentru acordarea badge-ului', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='badge',
            name='condition_value',
            field=models.IntegerField(blank=True, help_text='Valoarea minimă pentru acordarea badge-ului', null=True),
        ),
    ]
