# Generated by Django 5.2.5 on 2025-10-17 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosswords', '0003_challengeuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborative_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='challenge',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='difficulty',
            field=models.CharField(default='normal', max_length=32),
        ),
        migrations.AddField(
            model_name='challenge',
            name='progress_max',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='challenge',
            name='reward_badge',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='challenge',
            name='reward_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='reward_item',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='challenge',
            name='reward_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FriendChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'În așteptare'), ('accepted', 'Acceptată'), ('declined', 'Refuzată'), ('completed', 'Finalizată')], default='pending', max_length=16)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crosswords.challenge')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_challenges', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_challenges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
