# Generated by Django 5.2.5 on 2025-10-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crosswords', '0004_challenge_collaborators_challenge_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='puzzle',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='puzzles', to='crosswords.category'),
        ),
    ]
